[package]
name = "vcal-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = { version = "8", default-features = false, features = ["alloc"] }
time = { version = "0.3", default-features = false, features = ["parsing", "alloc"] }
heapless = "0.9"
log = "0.4"
